# Generated by Django 5.1.7 on 2025-04-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=2)),
                ('color', models.CharField(choices=[('White', 'White'), ('Black', 'Black'), ('Gray', 'Gray'), ('Beige', 'Beige'), ('Cream', 'Cream'), ('Navy', 'Navy'), ('Brown', 'Brown'), ('Red', 'Red'), ('Blue', 'Blue'), ('Yellow', 'Yellow'), ('Green', 'Green'), ('Orange', 'Orange'), ('Purple', 'Purple'), ('Olive', 'Olive'), ('Burgundy', 'Burgundy'), ('Pink', 'Pink'), ('Sky Blue', 'Sky Blue')], max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField(verbose_name='Price')),
            ],
        ),
    ]
